config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "prototypes#index"
  # resources :prototypes
  # resources :prototypes, only: [:new, :create, :show, :edit, :update, :destroy]
  # resources :comments, only: [:create]

  resources :prototypes do
    resources :comments, only: :create
  end  

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord

  # バリデーション
  validates :content, presence: true

  # アソシエーション
  belongs_to :prototype  # prototypeテーブルとのアソシエーション
  belongs_to :user       # usersテーブルとのアソシエーション
end

app/models/prototype.rb
class Prototype < ApplicationRecord
      belongs_to :user
      has_one_attached :image

      # バリデーション
      validates :title, presence: true
      validates :catch_copy, presence: true
      validates :concept, presence: true
      validates :image, presence: true

      # アソシエーション
      # has_many :comments    # commentsテーブルとのアソシエーション
      has_many :comments, dependent: :destroy    # commentsテーブルとのアソシエーション
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # Devise
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # バリデーション
  validates :name, presence: true
  validates :profile, presence: true
  validates :position, presence: true
  validates :occupation, presence: true

  # アソシエーション
  has_many :prototypes  # prototypesテーブルとのアソシエーション
  has_many :comments    # commentsテーブルとのアソシエーション
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :position, :occupation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # def create
  #   Comment.create(comment_params)
  # end

  # private
  # def comment_params
  #   params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  # end

  def create
    # Comment.create(comment_params)
    # comment = Comment.new(comment_params)
    # if comment.save
    #   redirect_to prototype_path(comment.prototype_id)
    # end   
    comment = Comment.create(comment_params)
      #redirect_to "/prototypes/#{comment.prototype.id}"     
    if comment.persisted?
      redirect_to "/prototypes/#{comment.prototype.id}"
    else
      # render "prototypes/show"
      @prototype = Prototype.find(params[:prototype_id])
      @comment = comment
      @comments = @prototype.comments.includes(:user)
      render "prototypes/show"
    end
  end
  
  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
  end


end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  #  before_action :authenticate_user!
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  #  必要があります。only オプションを指定しないと全てのアクションにログインが必要になってしまい、ログインしていないユーザーが index や show ページも見られなくなってしまいます。
  #  今回は new, create, edit, update, destroy のみログインを必須にしたいので only オプションで指定する必要があります。
  before_action :set_prototype, only: [:edit, :update, :destroy, :show]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    # @tweets = Tweet.all
    @prototypes = Prototype.all
  end

  def new
    @prototype = Prototype.new
  end

  def create
    @prototype = Prototype.new(prototype_params)
    #Prototype.create(prototype_params)    
    # redirect_to '/' 

    if @prototype.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # @prototype = Prototype.find(params[:id])
  end

  # def update
  #   tweet = Tweet.find(params[:id])
  #   tweet.update(tweet_params)
  #   redirect_to root_path
  # end

  # def update
  #   prototype = Prototype.find(params[:id])
  #   prototype.update(prototype_params)
  #   redirect_to prototype_path(prototype)
  # end

  def update
    @prototype = Prototype.find(params[:id])
    
    if @prototype.update(prototype_params)
      # 更新成功 → 詳細画面へ
      redirect_to prototype_path(@prototype)
    else
      # 更新失敗 → 編集画面を再表示
      render :edit
    end  
  end


  # def destroy
  #   tweet = Tweet.find(params[:id])
  #   tweet.destroy
  #   redirect_to root_path
  # end

  def destroy
    prototype = Prototype.find(params[:id])
    prototype.destroy
    redirect_to root_path
  end



  # prototypesコントローラーにshowアクションを設定した（まだアクション内の処理は書かない）
  # showアクションにインスタンス変数@prototypeを定義した。且つ、Pathパラメータで送信されるID値で、
  # Prototypeモデルの特定のオブジェクトを取得するように記述し、それを@prototypeに代入した
  def show
    @prototype = Prototype.find(params[:id])
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user)
    #必要かどうか不明のためコメントアウトしておく。
    #@comments = @prototype.comments.includes(:user)
  end

private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def move_to_index
    redirect_to root_path if current_user != @prototype.user
  end

  def prototype_params
    #https://master.tech-camp.in/v2/curriculums/8103
    #画像の保存を許可するストロングパラメーターにしましょう
    #params.require(:message).permit(:content, :image).merge(user_id: current_user.id)

    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :image
    ).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @prototypes = @user.prototypes
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Protospace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <%# ログインしているときは以下を表示するようにしましょう %> 
            <% if user_signed_in? %>
              <div class="nav__right">
                <span class="nav__greeting">
                <%#= "こんにちは #{current_user.name} さん" %>
                </span>

                <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: :nav__logout %>
                <%= link_to "New Proto", new_prototype_path, class: :nav__btn %>
                <%#= link_to "New Proto", root_path, class: :nav__btn %>
                
              </div>
            <% else %>
              <div class="nav__right">
                <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
                <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
              </div>
            <% end %>
            <%# <div class="nav__right"> %>
              <%# <%= link_to "ログアウト", root_path, class: :nav__logout %>
              <%# <%= link_to "New Proto", root_path, class: :nav__btn %>
            <%# </div> %>
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
            <%# 2026/02/04↓ %>
            <%# <div class="nav__right"> %>
              <%#= link_to "ログイン", root_path, class: :nav__btn %>
              <%#= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            <%# </div> %>
            <%# 2026/02/04↑ %>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%= form_with model: prototype, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "プロトタイプの名称" %><br />
    <%= f.text_field :title, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/_form.html_old.erb
<%= form_with(model: prototype, local: true) do |form| %>
  <%= form.text_field :image, placeholder: "Image Url" %>
  <%= form.text_area :text, placeholder: "text", rows: "10" %>
  <%= form.submit "SEND" %>
<% end %>

app/views/prototypes/_prototype.html.erb
<div class="card">
  <%#= link_to image_tag(prototype.image, class: :card__img), root_path%>
  <%= link_to image_tag(prototype.image, class: :card__img), prototype_path(prototype) %>

  <div class="card__body">
    <%= link_to prototype.title, root_path, class: :card__title%>
    <p class="card__summary">
      <%= prototype.catch_copy %>
    </p>
    <%= link_to "by #{prototype.user.name}", user_path(prototype.user), class: :card__user %>
    <%#= link_to "by #{prototype.user.name}", root_path, class: :card__user %>
  </div>
</div>



<%# https://master.tech-camp.in/v2/curriculums/4864 %>

      <!-- 投稿したユーザー名情報を出力する -->
      <%#= message.user.name %>

      <!-- 投稿した時刻を出力する -->
      <%#= message.created_at %>

      <!-- 投稿したメッセージ内容を記述する -->
      <%#= message.content %>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
        <%= link_to "#{current_user.name}さん", user_path(current_user), class: :greeting__link %>
        <%#= link_to "こんにちは#{current_user.name}さん", user_path(current_user), class: :greeting__link %>
        <%#= link_to "ユーザー名さん", root_path, class: :greeting__link%>
      </div>
    <% end %>  
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
      <%# https://master.tech-camp.in/v2/curriculums/8102 %>
      <%#= render partial: 'message', collection: @messages %>
      <%= render partial: "prototype", collection: @prototypes %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/new.html_old.erb
<%# <h1>New Proto</h1> %>
<%#= render "form" %>

<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= form_with(model: @prototype, local: true) do |form| %>
      <%= f.text_field :title %>
      <%= f.text_area :catch_copy %>
      <%= f.text_area :concept %>
      <%= form.submit "投稿" %>
    <% end %>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">

      <!-- プロトタイプ名 -->
      <p class="prototype__hedding">
        <%= @prototype.title %>
      </p>


      <!-- 投稿者 -->
      <%#= link_to "by #{@prototype.user.name}", root_path, class: :prototype__user %>
      <%= link_to "by #{@prototype.user.name}", user_path(@prototype.user), class: :prototype__user %>

      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user == @prototype.user %>
      <%# if user_signed_in? && current_user.id == tweet.user_id %>
        <div class="prototype__manage">
          <%#= link_to "編集する", root_path, class: :prototype__btn %>
          <%#= link_to '編集', edit_tweet_path(@tweet.id) %>
          <%= link_to "編集する", edit_prototype_path(@prototype), class: "prototype__btn" %>
          <%#= link_to '削除', tweet_path(@tweet.id), data: { turbo_method: :delete } %>
          <%#= link_to "削除する", root_path, class: :prototype__btn %>
          <%#= link_to "削除する", prototype_path(@prototype),method: :delete,class: :prototype__btn %>
          <%#= link_to '削除する', prototype_path(prototype.id), data: { turbo_method: :delete } %>
          <%= link_to "削除する", prototype_path(@prototype),data: { turbo_method: :delete },class: "prototype__btn" %>

          <%#= link_to '削除', tweet_path(tweet.id), data: { turbo_method: :delete } %>

        </div>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <% end %>

      <!-- 画像 -->
      <div class="prototype__image">
        <%= image_tag @prototype.image %>
      </div>

      <div class="prototype__body">

        <!-- キャッチコピー -->
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @prototype.catch_copy %>
          </p>
        </div>

        <!-- コンセプト -->
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.concept %>
          </p>
        </div>

      </div>

      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
        <% if user_signed_in? %>
          <%#= form_with model: モデル名,local: true do |f|%>
          <%= form_with model: [@prototype, @comment], local: true do |f| %>
            <div class="field">
              <%= f.label :content, "コメント" %><br />
              <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>

        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%# <%= " コメントのテキスト "%>
              <%= comment.content %>
              <%# <%= link_to "（ ユーザー名 ）", root_path, class: :comment_user %>
              <%#= link_to "（ #{comment.user.name} ）", root_path, class: :comment_user %>
              <%= link_to "（ #{comment.user.name} ）", user_path(comment.user), class: :comment_user %>
            </li>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報" %>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= @user.occupation %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= @user.position %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんのプロトタイプ" %>
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
        <%= render partial: "prototypes/prototype", collection: @prototypes %>
      </div>
    </div>
  </div>
</div>